// <auto-generated />
using LibraryManagementSystemUsingMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagementSystemUsingMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250325080742_seedOrAddDataToTable")]
    partial class seedOrAddDataToTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagementSystemUsingMVC.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BookData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F.Scott Fiztgerald",
                            BookTitle = "The Great Gatsby",
                            Genre = "Fiction",
                            Status = true,
                            Year = 1925
                        },
                        new
                        {
                            Id = 2,
                            Author = "Gorge Overwall",
                            BookTitle = "1984",
                            Genre = "Science Fiction",
                            Status = false,
                            Year = 1950
                        },
                        new
                        {
                            Id = 3,
                            Author = "Harper Lee",
                            BookTitle = "To Kill a Mockingbird",
                            Genre = "Fiction",
                            Status = true,
                            Year = 1960
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
